#!/usr/bin/env bash

set -euxo pipefail

DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

TO_BUILD=$(find . -maxdepth 1 -type d | grep -v -e '.git' -e '^.$')

for PKG in $TO_BUILD; do
	cd "$DIR/$PKG"
	makepkg -sc $@
done

cd "$DIR"